version: '3.4'

services:
  web:
    image: node:18-alpine
    ports:
      - '443:443'
    volumes:
      - ./vite-project:/usr/local/vite-project
    working_dir: /usr/local/vite-project
    command: sh -c "npm install && npm run dev"
